### ISSUE TITLE
I found a movie, but I wasn't able to add it

### ISSUE THREAD

**Issue by Shawn9347** [avraham/hass_radarr_sonarr_search_by_voice#16]
Hi, 
I am getting this error when testing the script manually. I don't know what could be wrong. radarr/sonarr are both on a different server than home assistant as you can see. They are in docker containers and those paths are the paths for radarr/sonarr. Do I add it like that or the complete path on the host server?

I used the api to get the profile id. It should be these numbers.

![config](https://user-images.githubusercontent.com/48714886/103437763-d1acce80-4c2b-11eb-845a-f93b43b2f1f4.png)
![error](https://user-images.githubusercontent.com/48714886/103437765-d40f2880-4c2b-11eb-9688-ba84b88896b1.png)

**Comment by avraham** [comment]
Hi,
What radarr version are you using?
Your paths should work like that.

**Comment by Shawn9347** [comment]
I am using radarr v3 and sonarr v3. I managed to fix the issue for radarr when testing the script manually. Doesn't work when talking to the google assistant however. Weirdly it's not working for sonarr when I test the script manually. I have everything the same as radarr and the right api key etc.

**Comment by avraham** [comment]
One possible problem is that I made these scripts for radarr v2 and sonarr
v2 and I haven't upgraded them. There are probably breaking changes in the
api v3.

How did you fix the issue with radarr?

There are a few things that can be the problem when adding a movie with
voice through Home Assistant.

If everything in the configuration file is correct, even when when adding a
movie manually it should send a feedback message through your smart
speaker. So, if this works the problem should be on IFTTT webhook /
automation part that runs the script by voice.

**Comment by Shawn9347** [comment]
I changed the script to work with https and added my domain urls. So it should work with v3. I have checked the scripts in home assistant like a 1000 times so yeah. I'll check again. Same ifftt.

**Comment by Shawn9347** [comment]
Is there any way to see logs?

**Comment by Shawn9347** [comment]
I fixed sonarr as well. Now the rest.

**Comment by avraham** [comment]
I have a modified version locally that has logs capabilities. I'll push the
change to GitHub in 1-2 days

**Comment by Shawn9347** [comment]
I got it working last night. It was too late to respond but here I am. Everything is working. Things I changed: I changed the python file to work with https. Put it my domain urls. Also at first I had the scripts path wrong. I thought I wasn't using docker but I forgot somehow. I have too many servers xD. So I changed the scripts path to /confing/scripts. the "/" in front is really important otherwise it doesn't work. Also you have to change the webhook url from homeassistant to your https url. And add external url in homeassistant for ifttt to work at all.

**Comment by AlexGreenUK** [comment]
@Rickexe I am having the same issue with the not being able to add it part and I also run Radarr/Sonarr V3. Would you mind giving a bit more detail about the parts you changed?

Thanks



> I got it working last night. It was too late to respond but here I am. Everything is working. Things I changed: I changed the python file to work with https. Put it my domain urls. Also at first I had the scripts path wrong. I thought I wasn't using docker but I forgot somehow. I have too many servers xD. So I changed the scripts path to /confing/scripts. the "/" in front is really important otherwise it doesn't work. Also you have to change the webhook url from homeassistant to your https url. And add external url in homeassistant for ifttt to work at all.

**Comment by Shawn9347** [comment]
Can you include screenshots of your config files? Do you have the external url set up in home assistant? Do you have your containers set up with https? I don't know if this is a must but for me it wasn't working with http.

**Comment by AlexGreenUK** [comment]
This config doesn't have the https but I have tried it with the https as well and I also edited the .py file and put the addresses in there instead of the variables.

When I ask it to download a movie I already have in radarr it tells me it's already there so I know it can see radarr. It's only when I try to add a movie that I don't have. I also have external URL set up.


![inCollage_20210113_133235729](https://user-images.githubusercontent.com/845591/104458889-de261500-55a3-11eb-9289-af1d3cc9c071.jpg)

**Comment by avraham** [comment]
Hi,
I'm testing with radarr v3 and it seems to work. With what movie are you testing it?

**Comment by spicerackk** [comment]
I am having the same issue as above. The script now works, it can detect if I have a movie in my list, however if it does find one, it is unable to add. I have 0 idea on how to modify python to allow https, an updated guide would be really helpful!

**Comment by avraham** [comment]
I updated the code. Update to the latest, add your  IP addresses with protocol https in the config file. Let's see if that fixes it.

**Comment by spicerackk** [comment]
ok will do, thank you!

**Comment by spicerackk** [comment]
Tried running again after updating and got this error:
 
```➜  hass_radarr_sonarr_search_by_voice git:(master) ✗ python3 ./hass_radarr_searc                                                                    h_by_voice.py "21 Bridges" "0"
21 Bridges
0
Warning. tmdmid_api_key_v3 (optional)(recommended) is not set. You won't be able                                                                     to search movies by actor or actress and your speaker's feedback will miss cast                                                                     details for movies. https://www.themoviedb.org/settings/api v3 auth
Traceback (most recent call last):
  File "./hass_radarr_search_by_voice.py", line 352, in <module>
    downloader = MovieDownloader(query, int(mode))
  File "./hass_radarr_search_by_voice.py", line 41, in __init__
    media_list = r.json()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)```

**Comment by avraham** [comment]
There's probably an error on your server_url value in the config file. It should look something like this.
[Radarr]
server_url = https://192.168.1.140:7878

Use http or https depending on your setup.

**Comment by spicerackk** [comment]
if i have a base URL set does that need to be put in also?

**Comment by spicerackk** [comment]
```[Radarr]
server_url = http://192.168.86.245:7878/radarr
api_key = *api_key*
root_directory = /mnt/media/Movies
profile_id = 4```

This is what I have tried, I'm not sure how to pull profile ID so could that be an issue?

**Comment by spicerackk** [comment]
Also getting an error saying something about `no connection adapters were found for '192.168.86.6:8123/api/services/tts/google_say'

**Comment by avraham** [comment]
So, if you put http://192.168.86.245:7878/radarr in the browser it loads the radarr UI, right?

About the profile_id, you can run the following on the command line. It will return an array of your radarr movies with several values, like "qualityProfileId", just copy the integer value of a movie that has the profile you use.

curl -X GET "http://localhost:7878/api/v3/movie?apiKey=API_KEY_HERE" -H "accept: application/json"

Make sure to replace it with your IP and API_KEY

**Comment by avraham** [comment]
If the command  `curl -X GET "http://localhost:7878/api/v3/movie?apiKey=API_KEY_HERE" -H "accept: application/json"` doesn't work, then your server_url value in the config file is also wrong. It will be the same base url right before the /api/ part.

**Comment by avraham** [comment]
> Also getting an error saying something about `no connection adapters were found for '192.168.86.6:8123/api/services/tts/google_say'

The value of tts_service in the config file should match of the Text to speech service_name on your home assistant configuration.yaml

Here's the important part of my configuration.yaml

>tts: 
>- platform: google_translate
>    cache: true
>    service_name: google_say

**Comment by spicerackk** [comment]
So my configuration.yaml looks like this:

```homeassistant:
  name: Home
  latitude: 
  longitude: 
  unit_system: metric
  time_zone: Australia/Sydney
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

plex_assistant:
  url: 'http://192.168.86.245:32400'
  token: 'token'
  default_cast: 'Lounge Room TV'
  language: 'en'
  tts_errors: true
  aliases:
    Lounge Room TV: Lounge Room TV
    Office Display: Office Display
    
    
conversation:
  intents:
    Plex:
     # These trigger commands can be changed to suit your needs.
     - "Tell Plex to {command}"
     - "{command} with Plex"

intent_script:
  Plex:
    speech:
      text: Command sent to Plex.
    action:
      service: plex_assistant.command
      data_template:
        command: "{{command}}"
        
automation:
  - alias: Plex Assistant Automation
    trigger:
    - event_data:
        action: call_service
      event_type: ifttt_webhook_received
      platform: event
    condition:
      condition: template
      value_template: "{{ trigger.event.data.service == 'plex_assistant.command' }}"
    action:
    - data_template:
        command: "{{ trigger.event.data.command }}"
      service_template: '{{ trigger.event.data.service }}'        
       
sensor:
- platform: plex_assistant
# Text to speech
tts:

- platform: google_translate
  cache: true
  service_name: google_say
  
  
group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
```

And I am still getting the above google_say error. I'm fairly new to HA, I am checking the configuration though and it says it's valid.

**Comment by spicerackk** [comment]
Ok, so, I got it working from Terminal, and I also have the IFTTT set up. If I ask my speaker to search for the series $, it responds like it should (Searching for $), but it doesn't add it to Sonarr or Radarr.

**Comment by spicerackk** [comment]
New error:

```
Traceback (most recent call last):
  File "./hass_radarr_search_by_voice.py", line 352, in <module>
    downloader = MovieDownloader(query, int(mode))
  File "./hass_radarr_search_by_voice.py", line 55, in __init__
    self.add_movie(data)
  File "./hass_radarr_search_by_voice.py", line 147, in add_movie
    with open(self.HASS_SCRIPTS_PATH+"/last_download_added.txt", "w") as myfile:
FileNotFoundError: [Errno 2] No such file or directory: '/config/scripts/last_download_added.txt'```

**Comment by spicerackk** [comment]
I'm also struggling to integrate it with HA, I am running Home Assistant OS on r-pi, but not sure how to copy the files across.

**Comment by avraham** [comment]
> New error:
> 
> ```
> Traceback (most recent call last):
>   File "./hass_radarr_search_by_voice.py", line 352, in <module>
>     downloader = MovieDownloader(query, int(mode))
>   File "./hass_radarr_search_by_voice.py", line 55, in __init__
>     self.add_movie(data)
>   File "./hass_radarr_search_by_voice.py", line 147, in add_movie
>     with open(self.HASS_SCRIPTS_PATH+"/last_download_added.txt", "w") as myfile:
> FileNotFoundError: [Errno 2] No such file or directory: '/config/scripts/last_download_added.txt'```
> ```

Ok. Home Assistant OS (hassos) Is relatively new and it wasn't around when I wrote the instructions. That error is because the file structure for hassos is different so the _scripts_path_ value changes too.

I don't have a hassos installation, but according to this (https://community.home-assistant.io/t/file-structure-in-hassos/194491) it should be "/mnt/data/supervisor/scripts". I'm taking a guess here. It's quite likely you will need to create the scripts directory.

About how to copy or access your Home Assistant config directory, you can install a Samba add-on like it says in this other forum question. (https://community.home-assistant.io/t/how-to-access-root-local-directory-to-insert-images-required-for-person-component/185427)

One important step is to give executable permissions. You might need to install an ssh add-on for that.

The script is still usable even with that error. It's just trying to save to a text file the movie id of the movie you just added to radarr in case you wish to implement a voice command to delete the last entry.
The full search option that gives you a list of movies won't work either, but we can sort that out later.

**Comment by ados8** [comment]
Having this very same issue.
Movie was found but cannot be added, have not configured any further as I can't get even the testing stage to work.
Using Radarr V3 and HTTP
Confirmed API key and tried through root console, HA docker and Radarr docker.

Even through Radarr container console it fails.
![image](https://user-images.githubusercontent.com/49982433/116015779-e51df280-a67d-11eb-85f2-ecbf5c76a3b0.png)

Really want to use this but few hours in and about to admit defeat.
