### ISSUE TITLE
Unable to get TV Show added from Speaker

### ISSUE THREAD

**Issue by sgtstadanko** [avraham/hass_radarr_sonarr_search_by_voice#18]
Hey. I updated to this latest code to get tv show added to the mix.  Basically redid everything from scratch.   Movie works perfectly, but TV show does not.  Google Assistant acts like it doesnt understand the command "Download TV Show $".  I never see it hitting ifttt trigger count on ifttt.com.  Any ideas where to look?  I have compared the applets visually and they are set up the same, same recipe, webhook and everything as movie except for trigger phrase and body.  Manual script runs from the home assistant over ssh add both movies and tv.

**Comment by sgtstadanko** [comment]
Ok. So two things.  1 - i had the script path wrong in ha_radarr_sonarr.conf.  Which not sure if that was issue because movies was working fine.   2- Changed trigger phrase in IFTTT from "Download TV Show" to "Download Show".  Oddly this fixed it.

**Comment by avraham** [comment]
Hi,
I'm glad you sorted it out.
Yes, it seems some triggers sentences sometimes are ignored by IFTTT. I
also had to change the trigger phrase of a previously working applet lately.
