### ISSUE TITLE
Cant seem to let the script work and actually download a movie 

### ISSUE THREAD

**Issue by mouledla** [avraham/hass_radarr_sonarr_search_by_voice#21]
I dont know if this project is still getting maintained, but i will still try and ask. 

So i have added all the config lines correctly, but it seems that the script doesnt do anything. You can see that it doesnt do anything in the picture below. Also no new movie added in radarr.
<img width="471" alt="image" src="https://user-images.githubusercontent.com/73481608/189766060-aa21a860-2049-49c1-b7b8-bec364867c2f.png">

This is my config file:

![image](https://user-images.githubusercontent.com/73481608/189766318-2814fe7c-46e8-41e1-8524-73939ba81adf.png)

Maybe someone could help me and get this to work, cuz i like it very much.

**Comment by avraham** [comment]
Hi,
I think it could be a problem with your server_url or api_key configuration.
I added more helpful messages printed in the console for easier troubleshooting.
Just download the latest version and try again :)

**Comment by mouledla** [comment]
Thanks for your response. I tried again with the latest version. But still no success. 
![image](https://user-images.githubusercontent.com/73481608/189784160-a9efdfea-0dfd-4e39-89eb-0f242f59ec67.png)

This is the logfile from radarr:
![image](https://user-images.githubusercontent.com/73481608/189784266-160df664-f3cc-48ab-a3b3-5c16fe6cb639.png)

maybe you will have an euraka moment, cuz i cant

**Comment by avraham** [comment]
What version of Radarr are you using?
The script was tested with V2 and v3

**Comment by mouledla** [comment]
![image](https://user-images.githubusercontent.com/73481608/189785829-c76ae628-d555-4ac1-b4dc-a2af04b38c87.png)

hmm that could be it indeed. I will test it with a seperate docker container but this time V3

**Comment by mouledla** [comment]
Unfortunately also with 3.0 and 3.2 does not work. Very weird. I am 100% accurate regarding the radarr url, port and api key. So i dont think it is that. If I look at Radarr logs, i see the following:
![image](https://user-images.githubusercontent.com/73481608/189788936-e554523d-cf3a-4c57-ab62-c4e0511d605c.png)

Why does it say "(removed)" at the api key part?

**Comment by mouledla** [comment]
For some reason, the test works for sonarr. but the radarr part does not work.

**Comment by mouledla** [comment]
I am using V3 now, and it kinda works. It just cant add a movie
![image](https://user-images.githubusercontent.com/73481608/189926829-b427401c-329b-4e5e-81f3-0920e44977f9.png)

**Comment by avraham** [comment]
Ok. Let me investigate what could be the problem

**Comment by avraham** [comment]
I added more debug messages in the latest version.
Now you need to execute it with the debug argument.
`python3 ./hass_radarr_search_by_voice.py "the avengers" "0" --debug`

It also prints out the http request made to the radarr server ready in curl format, so you can test it directly with curl in the command line.

As far as I can tell, the problem is in the http request to add the movie, maybe the rootFolderPath is not what radarr expects.

**Comment by mouledla** [comment]
Thanx for adding the debug part. This is what i get now. error statuscode 415
![image](https://user-images.githubusercontent.com/73481608/190155566-e87e93fa-4db1-4361-89c0-95aea90c6f0b.png)

A quick google search gives me the following:

The HTTP 415 Unsupported Media Type client error response code indicates that the server refuses to accept the request because the payload format is in an unsupported format. (maybe something wrong with the JSON payload?)

The format problem might be due to the request's indicated [Content-Type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) or [Content-Encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding), or as a result of inspecting the data directly.

**Comment by mouledla** [comment]
@avraham 

I followed these instructions: https://stackoverflow.com/questions/52216808/python-request-gives-415-error-while-post-data

And now it works.
![image](https://user-images.githubusercontent.com/73481608/190175013-3d6521a0-2975-4e1d-bf41-42db7e3b40a7.png)



I am no programming expert so please tell me if this is not the way of working ;) but I have added these lines:

![image](https://user-images.githubusercontent.com/73481608/190175327-60aa1617-6445-45e3-a6f0-f92c07199b64.png)


and with the post call where you add the movie, i have added the header parameters:
![image](https://user-images.githubusercontent.com/73481608/190175691-ba3b417a-4bfb-42be-babc-5629008404ce.png)



Without the debugging part you have added i wouldnt be able to find this, so thank you!

**Comment by avraham** [comment]
I'm glad you found a solution.
I believe some other people had the same issue in the past but I wasn't
able to reproduce it.
I'll add your fix ti the code. :)
