### ISSUE TITLE
Home Assistant cannot read repository info

### ISSUE THREAD

**Issue by bzellinger** [avraham/hass_radarr_sonarr_search_by_voice#5]
Thanks for sharing your add-on. I'm new to HA. 

I did some research and was directed to write the author of the add-on if there's issues with adding to HA. Can you tell me if there's an issue with my HA setup or if there's an issue adding this add-on? 

Here's the log: 

19-12-26 16:54:52 INFO (MainThread) [hassio.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
19-12-26 16:54:52 ERROR (MainThread) [hassio.utils.json] Can't read json from /data/addons/git/b202b002/repository.json: [Errno 2] No such file or directory: '/data/addons/git/b202b002/repository.json'
19-12-26 16:54:52 WARNING (MainThread) [hassio.store.data] Can't read repository information from /data/addons/git/b202b002/repository.json

**Comment by avraham** [comment]
Hi,
This is not an actual add-on for hassio. This is just a python script that you can run from Home Assistant.
This is how you [use it with a regular Home Assistant setup](https://github.com/avraham/hass_radarr_search_by_voice#integrate-with-home-assistant) 

hassio is an special version of Home Assistant but this should work too.

**Comment by bzellinger** [comment]
Thanks! I uploaded and I believe I configured the files correctly. Forgive my ignorance to HA and Linux in general. Perhaps I'm overlooking something. Here's the output when testing python3 ./hass_radarr_search_by_voice.py "star wars" "0": 

Command executed: python3 ./hass_radarr_search_by_voice.py "star wars" "0": 1
Traceback (most recent call last):
  File "./hass_radarr_search_by_voice.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

Any ideas? Thanks again!

**Comment by avraham** [comment]
It looks like executing python scripts within hassio can't import additional python modules.
As I'm not using hassio myself I'm not sure if it's possible or not.
A quick Google search found these home assistant threads.
[Python script import issues in hass.io](https://community.home-assistant.io/t/python-script-import-issues-in-hass-io/31787)
[HASSIO python scripts with imports](https://community.home-assistant.io/t/hassio-python-scripts-with-imports/45266)
Those might be helpful.

**Comment by bzellinger** [comment]
Thanks, I'll take a look. I appreciate the help.

**Comment by avraham** [comment]
Someone with a hassio setup made a guide and it's now merged into the project and instructions :)
