### ISSUE TITLE
Instructions for useage

### ISSUE THREAD

**Issue by vinistoisr** [avraham/hass_radarr_sonarr_search_by_voice#6]
I installed this but there seems to be some parts missing. 

I can search for movies by calling the python script as per the examples. 

How to call the script from homeassistant?

I'm trying everything to call the script in Developer tools and always get:

`Failed to call service script/download_movie. [Errno 8] Exec format error: '/config/scripts/download.sh'`

I'm trying things like { "movie": "star wars" } and all kinds of variations without any luck.  I'm sure I'm doing something stupid.

**Comment by avraham** [comment]
Hi,
Have you followed these steps?
[integrate-with-home-assistant](https://github.com/avraham/hass_radarr_search_by_voice#integrate-with-home-assistant)

I provide in the source code a folder example/homeassistant. There you can find the important parts for the scripts and shellcommand services. (Make sure to edit the path in the shellcommand.yaml file, full path may be required)

Here's how to test from within Home Assistant.
<img width="461" alt="Screen Shot 2020-04-06 at 4 33 08 PM" src="https://user-images.githubusercontent.com/2100103/78614823-90b29580-7824-11ea-89c3-40efec2e246c.png">

**Comment by colethegamer123** [comment]
I perfectly setup everything, but still has problems...

If I change the shell script to 
movie="star wars"
mode="0"

and I run the script.download_movie, then its working, but how should the get movie and mode get $1 and $2 from home assistant?

**Comment by colethegamer123** [comment]
I sorted it, its working from docker trough SSH.

I'll do some guide how I did it.
