### ISSUE TITLE
Getting error when trying test

### ISSUE THREAD

**Issue by colethegamer123** [avraham/hass_radarr_sonarr_search_by_voice#9]
Hello my friend,

I would really need this addon, would be very happy if I could make it work.

I filled out everything in the python file, but still nothing on HA side. 

First i wanted to test the other stuffs like radarr and apis.

Here is the error I get:

```
python3 ./hass_radarr_search_by_voice.py "star wars" "0"
star wars
0
Traceback (most recent call last):
  File "./hass_radarr_search_by_voice.py", line 294, in <module>
    downloader = MovieDownloader(query, int(mode))
  File "./hass_radarr_search_by_voice.py", line 61, in __init__
    r = requests.get("http://"+RADARR_SERVER+"/api/movie/lookup?apikey="+RADARR_API+"&term="+search_term)
AttributeError: module 'requests' has no attribute 'get'
```
RADARR_SERVER="192.168.0.20:7878" # with port
RADARR_API="7ac6FFFFFFFFFFFFFFFFFFFFFF"
RADARR_DOWNLOAD_PATH="/data/Movies" # aka rootFolderPath
RADARR_QUALITY_PROFILE_ID=5

TMDBID_API="bfeb64FFFFFFFFFFFFFFFFFF"

**Comment by avraham** [comment]
Hi,
Everything looks fine.
Do you have additional files at the same directory where this script file is?
This might be what's causing the error
[Stackoverflow solution](https://stackoverflow.com/questions/57458804/attributeerror-module-requests-has-no-attribute-post-is-it-deprecated-and)

**Comment by colethegamer123** [comment]
No, only the python file is inside.

**Comment by colethegamer123** [comment]
Stackoverflow solution tells you should edit the code, because its faulty. I do not know anything about python developing.

You see the same way?

**Comment by colethegamer123** [comment]
ImportError: cannot import name 'get' from 'requests' (unknown location)

**Comment by colethegamer123** [comment]
Problem was the requests module does not included GET. I reinstalled and its working.
